name: regression

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  keychain-creation:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: node keychain_creation.js 

  keychain-update:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: node keychain_update.js 

  send-uco:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: node send_uco.js 

  mint-fungible-token:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: node mint_fungible_token.js 

  mint-non-fungible-token:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: node mint_non_fungible_token.js 

  send-token:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: node send_token.js 

  deploy-contract:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - run: node deploy_contract.js 
